In [3]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [24]:
from sklearn.datasets import load_iris
import numpy as np

data = load_iris()

In [19]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

### Exercici 1
- Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [6]:
data.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
data.target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Exercici 2
- Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [8]:
print(data.data.ndim)
print(data.target.ndim)

print(data.data.shape)
print(data.target.shape)

new_data_target = np.concatenate((data.data, data.target.reshape(-1, 1)), axis=1)

2
1
(150, 4)
(150,)


In [9]:
new_data_target[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

### Exercici 3
- Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.



In [10]:
median_sepal_lenght = round(np.mean(data.data[:, 0], axis=0),2)
standard_deviation_sepal_lenght = round(np.std(data.data[:, 0], axis=0),2)
print(median_sepal_lenght)
print(standard_deviation_sepal_lenght)

median_petal_lenght = round(np.mean(data.data[:, 2], axis=0),2)
standard_deviation_petal_lenght = round(np.std(data.data[:, 2], axis=0),2)
print(median_petal_lenght)
print(standard_deviation_petal_lenght)

5.84
0.83
3.76
1.76


### Exercici 4
- Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [22]:
np.random.seed(42)

sample_indices = np.random.choice(new_data_target.shape[0], size=20, replace=False)
sample = new_data_target[sample_indices]

sample

array([[6.1, 2.8, 4.7, 1.2, 1. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.4, 2.8, 5.6, 2.2, 2. ]])

### Exercici 5

- Crea una matriu que mostri: 

- La mitjana de cada característica per espècie. 
- La desviació estàndard de cada característica per espècie.

In [21]:
print("setosa\n")
target_class = 'setosa'

setosa_data = data.data[data.target == data.target_names.tolist().index(target_class)]

setosa_mean_values = np.around(np.mean(setosa_data, axis=0), decimals=2)
print("La mitjana de cada característica de setosa és:")
print(setosa_mean_values)

setosa_stddev_values = np.around(np.std(setosa_data, axis=0), decimals=2)
print("La desviació estàndard de cada característica de setosa és:")
print(setosa_stddev_values)

print("\nversicolor\n")
target_class = 'versicolor'

versicolor_data = data.data[data.target == data.target_names.tolist().index(target_class)]

versicolor_mean_values = np.around(np.mean(versicolor_data, axis=0), decimals=2)
print("La mitjana de cada característica de versicolor és:")
print(versicolor_mean_values)

versicolor_stddev_values = np.around(np.std(versicolor_data, axis=0), decimals=2)
print("La desviació estàndard de cada característica de versicolor és:")
print(versicolor_stddev_values)

print("\nvirginica\n")
target_class = 'virginica'

virginica_data = data.data[data.target == data.target_names.tolist().index(target_class)]

virginica_mean_values = np.around(np.mean(virginica_data, axis=0), decimals=2)
print("La mitjana de cada característica de virginica és:")
print(virginica_mean_values)

virginica_stddev_values = np.around(np.std(virginica_data, axis=0), decimals=2)
print("La desviació estàndard de cada característica de virginica és:")
print(virginica_stddev_values)

setosa

La mitjana de cada característica de setosa és:
[5.01 3.43 1.46 0.25]
La desviació estàndard de cada característica de setosa és:
[0.35 0.38 0.17 0.1 ]

versicolor

La mitjana de cada característica de versicolor és:
[5.94 2.77 4.26 1.33]
La desviació estàndard de cada característica de versicolor és:
[0.51 0.31 0.47 0.2 ]

virginica

La mitjana de cada característica de virginica és:
[6.59 2.97 5.55 2.03]
La desviació estàndard de cada característica de virginica és:
[0.63 0.32 0.55 0.27]


### Exercici 6

- Calcula la quantitat de mostres per espècie.

In [20]:
species_variable_name = data.target

sample_sizes = np.bincount(species_variable_name)
species_names = data.target_names

for specie, size in enumerate(sample_sizes):
    specie_name = species_names[specie]
    print(f"La quantitat de mostres de {specie_name} és: {size}")

La quantitat de mostres de setosa és: 50
La quantitat de mostres de versicolor és: 50
La quantitat de mostres de virginica és: 50


- Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [19]:
species_data = data.data
species_variable_names = data.target

sepal_length_index = 0  
species = np.unique(species_variable_names)

mean_sepal_length_by_species = []
for specie in species:
    specie_data = species_data[species_variable_names == specie]
    mean_sepal_length = np.mean(specie_data[:, sepal_length_index])
    mean_sepal_length_by_species.append((specie, mean_sepal_length))

max_species, max_mean_sepal_length = max(mean_sepal_length_by_species, key=lambda x: x[1])

print(f"L'espècie amb el valor màxim de la mitjana de 'sepal length' és: {data.target_names[max_species]} amb una mitjana de {max_mean_sepal_length:.2f}")

L'espècie amb el valor màxim de la mitjana de 'sepal length' és: virginica amb una mitjana de 6.59


### Exercici 7

- Calcula la matriu de correlació entre les variables.

In [18]:
species_data = data.data

correlation_matrix = np.corrcoef(species_data, rowvar=False)

print("La matriu de correlació entre les variables és:")
print(correlation_matrix)

La matriu de correlació entre les variables és:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


- Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

In [16]:
species_data = data.data
species_variable_names = data.target

petal_length_index = 2  
species = np.unique(species_variable_names)

mean_petal_length_by_species = []

for specie in species:
    specie_data = species_data[species_variable_names == specie]
    mean_petal_length = np.mean(specie_data[:, petal_length_index])
    mean_petal_length_by_species.append((specie, mean_petal_length))

max_species, max_mean_petal_length = max(mean_petal_length_by_species, key=lambda species_data: species_data[1])

max_species_data = species_data[species_variable_names == max_species]

print(f"Els valors majors a la mitjana de la longitud de 'petal length' són per l'espècie {data.target_names[max_species]}:")
print(max_species_data)

Els valors majors a la mitjana de la longitud de 'petal length' són per l'espècie virginica:
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 

- Troba la mostra amb els pètals més grans.

In [17]:
species_data = data.data

max_petal_length_index = np.argmax(species_data[:, 2])

sample_with_max_petals = species_data[max_petal_length_index]

print("La mostra amb els pètals més grans és:")
print(sample_with_max_petals)

La mostra amb els pètals més grans és:
[7.7 2.6 6.9 2.3]


### Exercici 8
- Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [25]:
species_data = data.data
species_variable_names = data.target

sepal_length_index = 0  
petal_length_index = 2  
species = np.unique(species_variable_names)

mean_diff_by_species = []  

for specie in species:
    specie_data = species_data[species_variable_names == specie]
    
    mean_sepal_length = np.mean(specie_data[:, sepal_length_index])
    mean_petal_length = np.mean(specie_data[:, petal_length_index])
    
    mean_diff = mean_sepal_length - mean_petal_length
    mean_diff_by_species.append((specie, mean_diff))

max_species, max_mean_diff = max(mean_diff_by_species, key=lambda species_data: species_data[1])

print(f"L'espècie amb la major diferència entre la longitud mitjana de sèpals i pètals és {data.target_names[max_species]} amb una diferència de {max_mean_diff:.2f}")

L'espècie amb la major diferència entre la longitud mitjana de sèpals i pètals és setosa amb una diferència de 3.54
